import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavbarSection";
import Footer from "@/components/FooterSection";
import { getEntries } from "@/lib/contentful";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Rajesh Rajendran",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const links = await getEntries("links");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className=" flex  flex-col  items-center pt-28">
          <Navbar />
          {children}
          <Footer links={links} />
        </div>
      </body>
    </html>
  );
}
